### PR TITLE
feat: support various newline in vtt parsing

### PR DESCRIPTION
**Pull request by jeiea**
> A WebVTT line terminator consists of one of the following:
    - A U+000D CARRIAGE RETURN U+000A LINE FEED (CRLF) character pair.
    - A single U+000A LINE FEED (LF) character.
    - A single U+000D CARRIAGE RETURN (CR) character.

### CODE REVIEW

**Comment by shiyiya** [comment]
thx, Did all the tests pass?

**Comment by jeiea** [comment]
Of course. Still it's probably better to run it yourself.

**Comment by jeiea** [comment]
Added automated test for your sake.

**Comment by shiyiya** [comment]
thank u so mush!

**Comment by jeiea** [comment]
It seems Github actions did not run. Let me know if you find out why.

**Comment by shiyiya** [comment]
seem not enable ci for the project

**Pull request merged**
